export const chosungData = [ 
   {
    chosung: "ㅅㅇㅇ ㄷ",
    word: "서울의 달",
    hint1: "노래",
    hint2: "우리나라의 수도",
    hint3: "지구와 O",
  },{
  chosung: "ㄴㅇㅂㅂㄷ",
  word: "네이버밴드",
  hint1: "스마트폰",
  hint2: "정늠인이 모이는곳",
},
  {
    chosung: "ㅊㄱㅇ",
    word: "청기와",
    hint1: "지붕",
    hint2: "파란색",
    hint3: "옛날 외갓집, 민섭이 지섭이에게는 할머니집"
  },
  {
    chosung: "ㅅㅇㅇ ㄷ",
    word: "서울의 달",
    hint1: "노래",
    hint2: "우리나라의 수도",
    hint3: "지구와 O",
  },
  {
    chosung: "ㅅㅋㄹㅌㅅ",
    word: "소크라테스",
    hint1: "너 자신을 알라",
    hint2: "철학자",
  },
    {
      chosung: "ㅈㄴㅇ",
      word: "정늠인",
      hint1: "이정대 + 장순늠 = ?",
      hint2: "OOO의 마크는 네잎클로버다.",
    },
    {
      chosung: "ㄱㅂ",
      word: "김밥",
      hint1: "이영이 이모가 가장 잘 만드는 음식",
      hint2: "참치 OO, 계란 OO",
      hint3: "잘~~~ 말아 줘~~~",
    },
    {
      chosung: "ㄷㅈㅉㄱ",
      word: "된장찌개",
      hint1: "한국의 음식",
      hint2: "보글보글",
      hint3: "뚝배기",
    },
    {
      chosung: "ㅌㅅㅇ",
      word: "탕수육",
      hint1: "짜장면",
      hint2: "찍먹 부먹",
    },
    {
      chosung: "ㅇㅎㅅㅁㄱㅌㅇ",
      word: "월화수목금토일",
      hint1: "달력",
      hint2: "빨주노초파남보",
    },
    {
      chosung: "ㄱㄹ ㅆㅇㅇ ㅅㅇㄷ ㅌㅈㄷ",
      word: "고래 싸움에 새우등 터진다",
      hint1: "밥과 깡",
      hint2: "속담",
    },
    {
      chosung: "ㅈㄹㅇㄷ ㅂㅇㅁ ㄲㅌㅎㄷ",
      word: "지렁이도 밟으면 꿈틀한다",
      hint1: "속담",
      hint2: "비오는날 나타나는 이것에 관한 속담",
    },
    {
      chosung: "ㅂㄷㅂㅇㅁ",
      word: "불닭볶음면",
      hint1: "껍데기에 하얀닭이 그려져있음",
      hint2: "너무 매워",
      hint3: "라면",
    },
    {
      chosung: "ㄷㅇㄴㅁㅇㅌ",
      word: "다이너마이트",
      hint1: "한류열풍",
      hint2: "BTS",
    },
    {
      chosung: "ㄷㄱㅁㅅ",
      word: "대기만성",
      hint1: "사자성어",
      hint2: "큰 그릇은....",
      hint3: "큰 인물이 되려면 많은 시간이 필요하다",
    },
    {
      chosung: "ㄴㅂㄷㅂ",
      word: "노발대발",
      hint1: "노래한 손님이 주문한 음식에서 벌레가 나왔다고...OOOO했다.",
      hint2: "펄펄뛰다",
      hint3: "몹씨 성내다",
    },
    {
      chosung: "ㄴㄴㄸㄴ",
      word: "누네띠네",
      hint1: "체크무늬",
      hint2: "추억의",
      hint3: "과자",
    },
    {
      chosung: "ㅇㄷㅎㄹㅇㄱㅍㅍ",
      word: "응답하라1988",
      hint1: "지나간것은~~ 지나간대로~~",
      hint2: "진주",
      hint3: "덕선이",
    },

    {
      chosung: "ㅇㅌㅇㅋㄹㅅ",
      word: "이태원클라스",
      hint1: "드라마",
      hint2: "술집장사",
      hint3: "박새로이",
    },
    {
      chosung: "ㅇㅎㅇㅊ",
      word: "완행열차",
      hint1: "장윤정",
      hint2: "목포행",
      hint3: "느리게 칙칙폭폭",
    },
  ];